# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
        ('streams', '__first__'),
        ('clubs', '__first__'),
        ('squads', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1, verbose_name='Sex')),
                ('date_of_birth', models.DateField(default='1900-01-01', verbose_name='Date of birth')),
                ('squad_position', models.IntegerField(blank=True, default=-1, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AthletesImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Club', verbose_name='Club')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='athletes_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.AthletesImport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad', verbose_name='Squad'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream', verbose_name='Stream'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team', verbose_name='Team'),
        ),
    ]
