repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        files: \.(py|sh|rst|yml|yaml)$
    -   id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9
# Replaced by ruff:
# -   repo: https://github.com/PyCQA/flake8
#     rev: 6.0.0
#     hooks:
#     -   id: flake8
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        files: \.(py|sh|rst|yml|yaml)$
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.2
    hooks:
    -   id: poetry-check
        args: []
    -   id: poetry-lock
        args: [--no-update]
