[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
py_version = 39
line_length = 88
multi_line_output = 3
include_trailing_comma = true
profile='black'

[tool.flake8]
ignore = 'E203,E266,E501,W503'
max-line-length = 88
max-complexity = 18
select = 'B,C,E,F,W,T4'
# ALT: C4,C9 vs C
# ALSO: S
