# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10, verbose_name='Difficulty')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1, verbose_name='Sex')),
                ('minimum_year_of_birth', models.IntegerField(default=2000, verbose_name='Minimum Year of Birth')),
                ('all_around_individual', models.BooleanField(default=True, verbose_name='All around individual')),
                ('all_around_individual_counting_events', models.IntegerField(blank=True, default=4, null=True)),
                ('all_around_team', models.BooleanField(default=True, verbose_name='All around team')),
                ('all_around_team_size', models.IntegerField(blank=True, default=4, null=True)),
                ('all_around_team_counting_athletes', models.IntegerField(blank=True, default=4, null=True)),
                ('discipline_finals', models.BooleanField(default=False, verbose_name='Discipline finals')),
                ('discipline_finals_max_participants', models.IntegerField(blank=True, null=True)),
                ('discipline_finals_both_values_count', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=127)),
                ('discipline_set', models.ManyToManyField(through='common.StreamDisciplineJoin', to='common.Discipline')),
            ],
        ),
    ]
