# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=64, verbose_name='Contact name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('province', models.CharField(max_length=128, verbose_name='Province')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip code')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Value')),
                ('value_final', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Final Value')),
            ],
        ),
        migrations.CreateModel(
            name='StreamDisciplineJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Discipline')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
