# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('common', '0001_initial'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamdisciplinejoin',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream'),
        ),
        migrations.AddField(
            model_name='performance',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete', verbose_name='Athlete'),
        ),
        migrations.AddField(
            model_name='performance',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Discipline', verbose_name='Discipline'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('athlete', 'discipline')]),
        ),
    ]
